// Generated by gencpp from file robot_msgs/ClearErr.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_CLEARERR_H
#define ROBOT_MSGS_MESSAGE_CLEARERR_H

#include <ros/service_traits.h>


#include <robot_msgs/ClearErrRequest.h>
#include <robot_msgs/ClearErrResponse.h>


namespace robot_msgs
{

struct ClearErr
{

typedef ClearErrRequest Request;
typedef ClearErrResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearErr
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::ClearErr > {
  static const char* value()
  {
    return "76c68a2c5e109f4d6a4dc1cfc355f405";
  }

  static const char* value(const ::robot_msgs::ClearErr&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::ClearErr > {
  static const char* value()
  {
    return "robot_msgs/ClearErr";
  }

  static const char* value(const ::robot_msgs::ClearErr&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::ClearErrRequest> should match
// service_traits::MD5Sum< ::robot_msgs::ClearErr >
template<>
struct MD5Sum< ::robot_msgs::ClearErrRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::ClearErr >::value();
  }
  static const char* value(const ::robot_msgs::ClearErrRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::ClearErrRequest> should match
// service_traits::DataType< ::robot_msgs::ClearErr >
template<>
struct DataType< ::robot_msgs::ClearErrRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::ClearErr >::value();
  }
  static const char* value(const ::robot_msgs::ClearErrRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::ClearErrResponse> should match
// service_traits::MD5Sum< ::robot_msgs::ClearErr >
template<>
struct MD5Sum< ::robot_msgs::ClearErrResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::ClearErr >::value();
  }
  static const char* value(const ::robot_msgs::ClearErrResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::ClearErrResponse> should match
// service_traits::DataType< ::robot_msgs::ClearErr >
template<>
struct DataType< ::robot_msgs::ClearErrResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::ClearErr >::value();
  }
  static const char* value(const ::robot_msgs::ClearErrResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_CLEARERR_H
