// Generated by gencpp from file robot_msgs/SetAxis.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_SETAXIS_H
#define ROBOT_MSGS_MESSAGE_SETAXIS_H

#include <ros/service_traits.h>


#include <robot_msgs/SetAxisRequest.h>
#include <robot_msgs/SetAxisResponse.h>


namespace robot_msgs
{

struct SetAxis
{

typedef SetAxisRequest Request;
typedef SetAxisResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAxis
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::SetAxis > {
  static const char* value()
  {
    return "ba6aa16ce6b93641ff59c1e27e5efa94";
  }

  static const char* value(const ::robot_msgs::SetAxis&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::SetAxis > {
  static const char* value()
  {
    return "robot_msgs/SetAxis";
  }

  static const char* value(const ::robot_msgs::SetAxis&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::SetAxisRequest> should match
// service_traits::MD5Sum< ::robot_msgs::SetAxis >
template<>
struct MD5Sum< ::robot_msgs::SetAxisRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::SetAxis >::value();
  }
  static const char* value(const ::robot_msgs::SetAxisRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::SetAxisRequest> should match
// service_traits::DataType< ::robot_msgs::SetAxis >
template<>
struct DataType< ::robot_msgs::SetAxisRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::SetAxis >::value();
  }
  static const char* value(const ::robot_msgs::SetAxisRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::SetAxisResponse> should match
// service_traits::MD5Sum< ::robot_msgs::SetAxis >
template<>
struct MD5Sum< ::robot_msgs::SetAxisResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::SetAxis >::value();
  }
  static const char* value(const ::robot_msgs::SetAxisResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::SetAxisResponse> should match
// service_traits::DataType< ::robot_msgs::SetAxis >
template<>
struct DataType< ::robot_msgs::SetAxisResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::SetAxis >::value();
  }
  static const char* value(const ::robot_msgs::SetAxisResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_SETAXIS_H
