// Generated by gencpp from file robot_msgs/SetCollision.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_SETCOLLISION_H
#define ROBOT_MSGS_MESSAGE_SETCOLLISION_H

#include <ros/service_traits.h>


#include <robot_msgs/SetCollisionRequest.h>
#include <robot_msgs/SetCollisionResponse.h>


namespace robot_msgs
{

struct SetCollision
{

typedef SetCollisionRequest Request;
typedef SetCollisionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCollision
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::SetCollision > {
  static const char* value()
  {
    return "192c4b02f65b62b6f0470ca351b4f7cc";
  }

  static const char* value(const ::robot_msgs::SetCollision&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::SetCollision > {
  static const char* value()
  {
    return "robot_msgs/SetCollision";
  }

  static const char* value(const ::robot_msgs::SetCollision&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::SetCollisionRequest> should match
// service_traits::MD5Sum< ::robot_msgs::SetCollision >
template<>
struct MD5Sum< ::robot_msgs::SetCollisionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::SetCollision >::value();
  }
  static const char* value(const ::robot_msgs::SetCollisionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::SetCollisionRequest> should match
// service_traits::DataType< ::robot_msgs::SetCollision >
template<>
struct DataType< ::robot_msgs::SetCollisionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::SetCollision >::value();
  }
  static const char* value(const ::robot_msgs::SetCollisionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::SetCollisionResponse> should match
// service_traits::MD5Sum< ::robot_msgs::SetCollision >
template<>
struct MD5Sum< ::robot_msgs::SetCollisionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::SetCollision >::value();
  }
  static const char* value(const ::robot_msgs::SetCollisionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::SetCollisionResponse> should match
// service_traits::DataType< ::robot_msgs::SetCollision >
template<>
struct DataType< ::robot_msgs::SetCollisionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::SetCollision >::value();
  }
  static const char* value(const ::robot_msgs::SetCollisionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_SETCOLLISION_H
